name: NodeRED-Hackathon-Handwerk-Stack
description: NodeRED Stack für den Hackathon Handwerk
version: 0.0.1
category: Applications
maintainer: Patrick Nitschke
license: The MIT License
projectURL: https://github.com/patrick-nits/rancher-custom-catalog.git