name: NodeRED-Hackathon-Handwerk-Stack
description: |
  # Description of the Catalog Entry
version: 0.0.1
category: Databases
maintainer: Patrick Nitschke
license: The MIT License
projectURL: https://github.com/patrick-nits/rancher-custom-catalog.git