version: "2"
catalog:
  name: NodeRED-Hackathon-Handwerk-Stack
  version: 0.0.1
  maintainer: "Patrick Nitschke"
  questions:
    - variable: "volumedriver"
      description: "Choose the Volume Driver being used.(Option: local or rancher-nfs)"
      label: "Volume Driver:"
      required: true
      default: rancher-nfs
      type: "enum"
      options:
        - local
        - rancher-nfs
    - variable: username
      label: "Benutzername"
      description: "Benutzername for MariaDB, MongoDB, Adminer, AdminMongo"
      default: "root"
      type: string 
    - variable: password
      label: "Passwords"
      description: "Password for MariaDB, MongoDB, Adminer, AdminMongo"
      default: "changeMechangeMe"
      type: string 
    - variable: db
      label: "Database"
      description: "Database name for MariaDB, MongoDB"
      default: "hackathon-handwerk"
      type: string 
    - variable: team
      label: "Team"
      description: "Hackathon Handwerk Team"
      default: "changeMe"
      type: string 
services:
  node-red:
    scale: 1
    retain_ip: true
  maria-db:
    scale: 1
    retain_ip: true
  maria-db-management:
    scale: 1
    retain_ip: true
  mongo-db:
    scale: 1
    retain_ip: true
  mongo-db-management:
    scale: 1
    retain_ip: true
  node-red-stack-lb:
    depends_on: 
      - node-red
    scale: 1
    lb_config:
      certs: []
      port_rules:
      - protocol: http
        hostname: ${team}.rancher.hackathon-handwerk.de
        service: node-red
        source_port: 80
        target_port: 1880
      - protocol: http
        hostname: mariadb.${team}.rancher.hackathon-handwerk.de
        service: maria-db-management
        source_port: 80
        target_port: 8080
      - protocol: http
        hostname: mongodb.${team}.rancher.hackathon-handwerk.de
        service: mongodb-db-management
        source_port: 80
        target_port: 1234