version: "2"
catalog:
  name: NodeRED-Hackathon-Handwerk-Stack
  version: 0.0.1
  maintainer: "Patrick Nitschke"
  questions:
    - variable: "volumedriver"
      description: "Choose the Volume Driver being used.(Option: local or rancher-nfs)"
      label: "Volume Driver:"
      required: true
      default: rancher-nfs
      type: "enum"
      options:
        - local
        - rancher-nfs
    - variable: username
      label: "Benutzername"
      description: "Benutzername for MariaDB, MongoDB, Adminer, AdminMongo"
      default: "root"
      type: string 
    - variable: password
      label: "Passwords"
      description: "Password for MariaDB, MongoDB, Adminer, AdminMongo"
      default: "changeMechangeMe"
      type: string 
    - variable: db
      label: "Database"
      description: "Database name for MariaDB, MongoDB"
      default: "hackathon-handwerk"
      type: string 
    - variable: team
      label: "Team"
      description: "Hackathon Handwerk Team"
      default: "changeMe"
      type: string 
services:
  mongo-db:
    retain_ip: true
    scale: 1
    start_on_create: true
  node-red:
    retain_ip: true
    scale: 1
    start_on_create: true
  mongo-db-management:
    retain_ip: true
    scale: 1
    start_on_create: true
  maria-db:
    retain_ip: true
    scale: 1
    start_on_create: true
  maria-db-management:
    retain_ip: true
    scale: 1
    start_on_create: true
  node-red-stack-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ${team}.rancher.hackathon-handwerk.de
        path: ''
        priority: 1
        protocol: http
        service: node-red
        source_port: 80
        target_port: 1880
      - hostname: mariadb.${team}.rancher.hackathon-handwerk.de
        priority: 2
        protocol: http
        service: maria-db-management
        source_port: 80
        target_port: 8080
      - hostname: mongodb.${team}.rancher.hackathon-handwerk.de
        priority: 3
        protocol: http
        service: mongo-db-management
        source_port: 80
        target_port: 1234
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000