name: Alfresco-CE-EIM
description: Alfresco CE Stack for EIM
version: 0.0.1
category: Applications
maintainer: Patrick Nitschke
license: The MIT License
projectURL: https://github.com/patrick-nits/rancher-custom-catalog.git
